package View;

import Model.Book;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.swing.*;

public class BookCard extends javax.swing.JPanel {
    private Book book;
    private final Color defaultBg = new Color(255, 255, 255, 35);
    private final Color hoverBg = new Color(255, 255, 255, 60);
    private final Color borderColor = new Color(255, 255, 255, 75);
    private final Color hoverBorderColor = new Color(255, 220, 100, 200);
    private boolean isHovered = false;

    // Zero-parameter constructor required by NetBeans GUI Builder
    public BookCard() {
        initComponents();
        setOpaque(false);
    }

    public BookCard(Book book) {
        this.book = book;
        initComponents();
        setOpaque(false);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        setupCard();
    }

    private void setupCard() {
        if (book == null) return;
        
        // Setup Title
        String displayText;
        if (book.isFutureRelease()) {
            displayText = "<html><body style='text-align: center;'>Title: " + book.getTitle() + " (" + book.getYear() + ")</body></html>";
        } else {
            displayText = "<html><body style='text-align: center;'>Title: " + book.getTitle() + "</body></html>";
        }
        titleLabel.setText(displayText);

        // Setup Image
        loadCoverImage();

        // Mouse Listeners for visual hover feedback
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                isHovered = true;
                repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                isHovered = false;
                repaint();
            }
        });
    }

    private void loadCoverImage() {
        int width = 130;
        int height = 175;
        try {
            String path = "/images/" + book.getImagePath();
            URL imgUrl = getClass().getResource(path);
            if (imgUrl != null) {
                ImageIcon icon = new ImageIcon(imgUrl);
                Image img = icon.getImage();
                Image scaledImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                imageLabel.setIcon(new ImageIcon(scaledImg));
            } else {
                imageLabel.setIcon(new ImageIcon(createPlaceholderCover(book.getTitle(), width, height)));
            }
        } catch (Exception e) {
            imageLabel.setIcon(new ImageIcon(createPlaceholderCover(book.getTitle(), width, height)));
        }
    }

    private Image createPlaceholderCover(String title, int width, int height) {
        BufferedImage img = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = img.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        GradientPaint gp = new GradientPaint(0, 0, new Color(48, 43, 99), 0, height, new Color(15, 12, 75));
        g2.setPaint(gp);
        g2.fillRoundRect(0, 0, width, height, 10, 10);

        g2.setColor(new Color(255, 255, 255, 40));
        g2.drawRoundRect(0, 0, width - 1, height - 1, 10, 10);
        g2.fillRect(5, 5, 2, height - 10);

        g2.setColor(Color.WHITE);
        g2.setFont(new Font("Cambria Math", Font.BOLD, 12));
        FontMetrics fm = g2.getFontMetrics();
        
        String[] words = title.split(" ");
        int y = 50;
        for (String word : words) {
            int stringWidth = fm.stringWidth(word);
            int x = (width - stringWidth) / 2;
            g2.drawString(word, x, y);
            y += fm.getHeight();
            if (y > height - 20) break;
        }

        g2.dispose();
        return img;
    }

    public Book getBook() {
        return book;
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.setColor(isHovered ? hoverBg : defaultBg);
        g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), 15, 15));

        g2.setColor(isHovered ? hoverBorderColor : borderColor);
        g2.setStroke(new BasicStroke(isHovered ? 2f : 1f));
        g2.draw(new RoundRectangle2D.Float(0, 0, getWidth() - 1, getHeight() - 1, 15, 15));

        g2.dispose();
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(160, 240));
        setLayout(null);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(imageLabel);
        imageLabel.setBounds(10, 10, 140, 180);

        titleLabel.setFont(new java.awt.Font("Cambria Math", 2, 13)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Title");
        add(titleLabel);
        titleLabel.setBounds(10, 195, 140, 35);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
