/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author asus
 */
public class borrowbook extends javax.swing.JPanel {

    /**
     * Creates new form borrowbook
     */
    public borrowbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(null);

        jButton1.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Dashboard");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setContentAreaFilled(false);
        add(jButton1);
        jButton1.setBounds(0, 0, 190, 110);

        jButton2.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Catalog");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setContentAreaFilled(false);
        add(jButton2);
        jButton2.setBounds(0, 110, 190, 110);

        jButton3.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("My books");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.setContentAreaFilled(false);
        add(jButton3);
        jButton3.setBounds(0, 220, 190, 110);

        jButton4.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Payments");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);
        add(jButton4);
        jButton4.setBounds(0, 330, 190, 110);

        jButton5.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Logout");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        add(jButton5);
        jButton5.setBounds(0, 440, 190, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background image of lms-2---new.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 190, 700);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("My Books");
        add(jTextField1);
        jTextField1.setBounds(270, 40, 160, 70);

        jButton6.setFont(new java.awt.Font("Cambria Math", 3, 17)); // NOI18N
        jButton6.setText("Borrowed");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(215, 215, 20), 2, true));
        jButton6.setOpaque(true);
        add(jButton6);
        jButton6.setBounds(220, 180, 230, 80);

        jButton7.setFont(new java.awt.Font("Cambria Math", 3, 17)); // NOI18N
        jButton7.setText("Returned");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(214, 214, 21), 2, true));
        add(jButton7);
        jButton7.setBounds(480, 180, 230, 80);

        jButton8.setFont(new java.awt.Font("Cambria Math", 3, 17)); // NOI18N
        jButton8.setText("History");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(214, 214, 21), 2, true));
        add(jButton8);
        jButton8.setBounds(730, 180, 230, 80);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book Tittle", "Author", "Borrowed On", "Due Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(220, 320, 950, 300);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroud photo of library management system-new.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(1200, 700));
        add(jLabel3);
        jLabel3.setBounds(0, -20, 1220, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
