package View;

import Model.Book;
import java.awt.*;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.List;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

public class CatalogView extends javax.swing.JFrame {

    // Sprint 2: Search book query input
    public CatalogView() {
        initComponents();
        setupDesign();
    }

    private void setupDesign() {
        ViewUtils.applySharedDesign(this, sidebarPanel, mainPanel, bgLabel, btnLogout,
            new javax.swing.JButton[]{btnDashboard, btnCatalog, btnMyBooks, btnPayments}, btnCatalog);

        futureScrollPane.getViewport().setOpaque(false);
        catalogScrollPane.getViewport().setOpaque(false);

        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ViewUtils.handleResize(CatalogView.this, sidebarPanel, mainPanel, bgLabel, btnLogout);

                int w = getContentPane().getWidth();
                int h = getContentPane().getHeight();
                if (w <= 0 || h <= 0) return;

                int mainW = w - 220;
                int contentW = mainW - 60; // 30 margin left and right
                
                lblTitle.setBounds(30, 20, contentW, 50);
                lblSubheader.setBounds(30, 70, contentW, 30);
                futureScrollPane.setBounds(30, 110, contentW, 270);
                searchBarPanel.setBounds(30, 390, contentW, 40);
                catalogScrollPane.setBounds(30, 440, contentW, h - 470);
                
                revalidate();
                repaint();
            }
        });
    }

    // Dynamic lists population
    public void setFutureReleases(List<Book> books, java.awt.event.MouseListener clickListener) {
        futureReleasesContainer.removeAll();
        int cardWidth = 160;
        int gap = 15;
        int totalWidth = books.size() * (cardWidth + gap) + gap;
        futureReleasesContainer.setPreferredSize(new java.awt.Dimension(totalWidth, 250));

        for (Book book : books) {
            BookCard card = new BookCard(book);
            if (clickListener != null) {
                card.addMouseListener(clickListener);
            }
            futureReleasesContainer.add(card);
        }
        futureReleasesContainer.revalidate();
        futureReleasesContainer.repaint();
    }

    public void setCatalogBooks(List<Book> books, java.awt.event.MouseListener clickListener) {
        catalogContainer.removeAll();
        int cardWidth = 160;
        int cardHeight = 240;
        int gap = 15;
        int containerWidth = catalogScrollPane.getWidth() - 20;
        if (containerWidth <= 0) {
            containerWidth = 880; // Default fallback
        }
        int cols = Math.max(1, containerWidth / (cardWidth + gap));
        int rows = (int) Math.ceil(books.size() / (double) cols);
        int totalHeight = rows * (cardHeight + gap) + gap;
        catalogContainer.setPreferredSize(new java.awt.Dimension(containerWidth, totalHeight));

        for (Book book : books) {
            BookCard card = new BookCard(book);
            if (clickListener != null) {
                card.addMouseListener(clickListener);
            }
            catalogContainer.add(card);
        }
        catalogContainer.revalidate();
        catalogContainer.repaint();
    }

    // Getters and Listeners (Flow Step 4)
    public JTextField getSearchField() {
        return txtSearch;
    }

    public JComboBox<String> getGenreComboBox() {
        return cbGenre;
    }

    public void addSearchListener(ActionListener listener) {
        btnSearch.addActionListener(listener);
        txtSearch.addActionListener(listener); // trigger search on Enter
    }

    public void addGenreFilterListener(ActionListener listener) {
        cbGenre.addActionListener(listener);
        btnFilter.addActionListener(listener);
    }

    public void addDashboardListener(ActionListener listener) {
        btnDashboard.addActionListener(listener);
    }

    public void addMyBooksListener(ActionListener listener) {
        btnMyBooks.addActionListener(listener);
    }

    public void addPaymentsListener(ActionListener listener) {
        btnPayments.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        btnLogout.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        sidebarPanel = new View.TranslucentPanel();
        btnDashboard = new javax.swing.JButton();
        btnCatalog = new javax.swing.JButton();
        btnMyBooks = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubheader = new javax.swing.JLabel();
        futureScrollPane = new javax.swing.JScrollPane();
        futureReleasesContainer = new javax.swing.JPanel();
        searchBarPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbGenre = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        catalogScrollPane = new javax.swing.JScrollPane();
        catalogContainer = new javax.swing.JPanel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        sidebarPanel.setOpaque(false);
        sidebarPanel.setLayout(null);

        btnDashboard.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("🏠 Dashboard");
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnDashboard);
        btnDashboard.setBounds(10, 50, 200, 45);

        btnCatalog.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        btnCatalog.setForeground(new java.awt.Color(255, 255, 255));
        btnCatalog.setText("📚 Catalog");
        btnCatalog.setContentAreaFilled(false);
        btnCatalog.setFocusPainted(false);
        btnCatalog.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnCatalog);
        btnCatalog.setBounds(10, 110, 200, 45);

        btnMyBooks.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        btnMyBooks.setForeground(new java.awt.Color(255, 255, 255));
        btnMyBooks.setText("📖 My Books");
        btnMyBooks.setContentAreaFilled(false);
        btnMyBooks.setFocusPainted(false);
        btnMyBooks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnMyBooks);
        btnMyBooks.setBounds(10, 170, 200, 45);

        btnPayments.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        btnPayments.setForeground(new java.awt.Color(255, 255, 255));
        btnPayments.setText("💳 Payments");
        btnPayments.setContentAreaFilled(false);
        btnPayments.setFocusPainted(false);
        btnPayments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnPayments);
        btnPayments.setBounds(10, 230, 200, 45);

        btnLogout.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("🚪 Logout");
        btnLogout.setContentAreaFilled(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnLogout);
        btnLogout.setBounds(10, 600, 200, 45);

        getContentPane().add(sidebarPanel);
        sidebarPanel.setBounds(0, 0, 220, 700);

        mainPanel.setOpaque(false);
        mainPanel.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Cambria Math", 1, 42)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Book Catalog");
        mainPanel.add(lblTitle);
        lblTitle.setBounds(30, 20, 350, 50);

        lblSubheader.setFont(new java.awt.Font("Cambria Math", 2, 22)); // NOI18N
        lblSubheader.setForeground(new java.awt.Color(255, 255, 255));
        lblSubheader.setText("Future releases");
        mainPanel.add(lblSubheader);
        lblSubheader.setBounds(30, 70, 200, 30);

        futureScrollPane.setBorder(null);
        futureScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        futureScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        futureScrollPane.setOpaque(false);

        futureReleasesContainer.setOpaque(false);
        futureReleasesContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));
        futureScrollPane.setViewportView(futureReleasesContainer);

        mainPanel.add(futureScrollPane);
        futureScrollPane.setBounds(30, 110, 900, 270);

        searchBarPanel.setOpaque(false);
        searchBarPanel.setLayout(null);
        searchBarPanel.add(txtSearch);
        txtSearch.setBounds(0, 5, 300, 30);

        btnSearch.setBackground(new java.awt.Color(237, 226, 66));
        btnSearch.setText("🔍");
        searchBarPanel.add(btnSearch);
        btnSearch.setBounds(310, 5, 35, 30);

        cbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Genres", "Fantasy", "Sci-Fi", "Classic", "Detective", "Fiction" }));
        searchBarPanel.add(cbGenre);
        cbGenre.setBounds(400, 5, 150, 30);

        btnFilter.setBackground(new java.awt.Color(237, 226, 66));
        btnFilter.setText("⚙");
        searchBarPanel.add(btnFilter);
        btnFilter.setBounds(560, 5, 35, 30);

        mainPanel.add(searchBarPanel);
        searchBarPanel.setBounds(30, 390, 900, 40);

        catalogScrollPane.setBorder(null);
        catalogScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        catalogScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        catalogScrollPane.setOpaque(false);

        catalogContainer.setOpaque(false);
        catalogContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));
        catalogScrollPane.setViewportView(catalogContainer);

        mainPanel.add(catalogScrollPane);
        catalogScrollPane.setBounds(30, 440, 900, 230);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(220, 30, 980, 700);

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (5).png"))); // NOI18N
        getContentPane().add(bgLabel);
        bgLabel.setBounds(0, 0, 1200, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JButton btnCatalog;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyBooks;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel catalogContainer;
    private javax.swing.JScrollPane catalogScrollPane;
    private javax.swing.JComboBox<String> cbGenre;
    private javax.swing.JPanel futureReleasesContainer;
    private javax.swing.JScrollPane futureScrollPane;
    private javax.swing.JLabel lblSubheader;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel searchBarPanel;
    private View.TranslucentPanel sidebarPanel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            CatalogView cv = new CatalogView();
            Controller.CatalogController cc = new Controller.CatalogController(cv, new Model.userdata("TestUser", "test@lms.com", ""));
            cc.open();
        });
    }
}
