/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 * Swing User Interface for resetting lost user passwords.
 * 
 * @author aadha
 */
public class ForgotPassword extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPassword.class.getName());

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        
        // Maximize window
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        // Cozy library theme: brown transparent background for panel
        jPanel2.setBackground(new Color(40, 20, 10, 185));
        jPasswordFieldNew.setText("");
        jPasswordFieldConfirm.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelSubtitle = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNewPassword = new javax.swing.JLabel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldNew = new javax.swing.JPasswordField();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jButtonReset = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Forgot Password");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(460, 160, 400, 50);

        jLabelSubtitle.setFont(new java.awt.Font("Cambria Math", 2, 14)); // NOI18N
        jLabelSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubtitle.setText("Reset your account password");
        getContentPane().add(jLabelSubtitle);
        jLabelSubtitle.setBounds(460, 210, 400, 20);

        jLabelEmail.setFont(new java.awt.Font("Cambria Math", 2, 16)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(470, 250, 150, 25);

        jLabelNewPassword.setFont(new java.awt.Font("Cambria Math", 2, 16)); // NOI18N
        jLabelNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNewPassword.setText("New Password");
        getContentPane().add(jLabelNewPassword);
        jLabelNewPassword.setBounds(470, 290, 150, 25);

        jLabelConfirmPassword.setFont(new java.awt.Font("Cambria Math", 2, 16)); // NOI18N
        jLabelConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirmPassword.setText("Confirm Password");
        getContentPane().add(jLabelConfirmPassword);
        jLabelConfirmPassword.setBounds(470, 330, 150, 25);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(650, 250, 190, 25);

        jPasswordFieldNew.setText("jPasswordFieldNew");
        getContentPane().add(jPasswordFieldNew);
        jPasswordFieldNew.setBounds(650, 290, 190, 25);

        jPasswordFieldConfirm.setText("jPasswordFieldConfirm");
        getContentPane().add(jPasswordFieldConfirm);
        jPasswordFieldConfirm.setBounds(650, 330, 190, 25);

        jButtonReset.setBackground(new java.awt.Color(237, 226, 66));
        jButtonReset.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButtonReset.setText("Reset Password");
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(530, 380, 260, 35);

        jButtonBack.setFont(new java.awt.Font("Cambria Math", 2, 16)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 234, 0));
        jButtonBack.setText("Back to Login");
        jButtonBack.setContentAreaFilled(false);
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(530, 430, 260, 30);

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 234, 0), 5));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design.png"))); // NOI18N
        jPanel2.add(jLabelLogo);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(430, 70, 460, 490);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (5).png"))); // NOI18N
        jLabelBackground.setPreferredSize(new java.awt.Dimension(1700, 700));
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 1700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JTextField getEmailField() {
        return jTextFieldEmail;
    }

    public javax.swing.JPasswordField getNewPasswordField() {
        return jPasswordFieldNew;
    }

    public javax.swing.JPasswordField getConfirmPasswordField() {
        return jPasswordFieldConfirm;
    }

    public void addResetPasswordListener(java.awt.event.ActionListener listener) {
        jButtonReset.addActionListener(listener);
    }

    public void addBackToLoginListener(java.awt.event.ActionListener listener) {
        jButtonBack.addActionListener(listener);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNewPassword;
    private javax.swing.JLabel jLabelSubtitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldConfirm;
    private javax.swing.JPasswordField jPasswordFieldNew;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
