/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author aadha
 */
public class UserSignUp extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserSignUp.class.getName());

    /**
     * Creates new form UserSignUp
     */
    public UserSignUp() {
        initComponents();
        
        // Maximize window
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        // Semi-transparent cozy library aesthetic background for panel
        jPanel2.setBackground(new Color(40, 20, 10));
        jPanel2.setAlpha(185);
        jPasswordFieldPassword.setText("");
        jPasswordFieldConfirm.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelSubtitle = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jButtonCreate = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabelPassword = new javax.swing.JLabel();
        jPanel2 = new View.TranslucentPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Create Your Account");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(500, 200, 400, 50);

        jLabelSubtitle.setFont(new java.awt.Font("Cambria Math", 2, 14)); // NOI18N
        jLabelSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubtitle.setText("Fill in the details below to get started");
        getContentPane().add(jLabelSubtitle);
        jLabelSubtitle.setBounds(500, 250, 400, 20);

        jLabelName.setFont(new java.awt.Font("Cambria Math", 2, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Name");
        getContentPane().add(jLabelName);
        jLabelName.setBounds(360, 290, 60, 30);
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(450, 290, 210, 30);

        jLabelEmail.setFont(new java.awt.Font("Cambria Math", 2, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(680, 290, 40, 30);

        jLabelConfirmPassword.setFont(new java.awt.Font("Cambria Math", 2, 14)); // NOI18N
        jLabelConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirmPassword.setText("Confirm Password");
        getContentPane().add(jLabelConfirmPassword);
        jLabelConfirmPassword.setBounds(680, 340, 120, 30);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(800, 290, 190, 30);
        getContentPane().add(jPasswordFieldPassword);
        jPasswordFieldPassword.setBounds(450, 340, 210, 30);
        getContentPane().add(jPasswordFieldConfirm);
        jPasswordFieldConfirm.setBounds(800, 340, 190, 30);

        jButtonCreate.setBackground(new java.awt.Color(237, 226, 66));
        jButtonCreate.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButtonCreate.setText("Create Account");
        getContentPane().add(jButtonCreate);
        jButtonCreate.setBounds(570, 410, 260, 40);

        jButtonLogin.setFont(new java.awt.Font("Cambria Math", 2, 16)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 234, 0));
        jButtonLogin.setText("Already have an account? Login");
        jButtonLogin.setContentAreaFilled(false);
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(570, 470, 250, 30);

        jLabelPassword.setFont(new java.awt.Font("Cambria Math", 2, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword);
        jLabelPassword.setBounds(360, 340, 70, 30);

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 234, 0), 5));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design.png"))); // NOI18N
        jPanel2.add(jLabelLogo);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(320, 70, 760, 500);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (5).png"))); // NOI18N
        jLabelBackground.setPreferredSize(new java.awt.Dimension(1700, 700));
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 1700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JTextField getNameField() {
        return jTextFieldName;
    }

    public javax.swing.JTextField getEmailField() {
        return jTextFieldEmail;
    }

    public javax.swing.JPasswordField getPasswordField() {
        return jPasswordFieldPassword;
    }

    public javax.swing.JPasswordField getConfirmPasswordField() {
        return jPasswordFieldConfirm;
    }

    public void addCreateAccountListener(java.awt.event.ActionListener listener) {
        jButtonCreate.addActionListener(listener);
    }

    public void addLoginListener(java.awt.event.ActionListener listener) {
        jButtonLogin.addActionListener(listener);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserSignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSubtitle;
    private javax.swing.JLabel jLabelTitle;
    private View.TranslucentPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldConfirm;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
